In [379]:
import csv
import shutil
import pandas as pd
import math

In [380]:
Original = r'C:\Users\mackt\Python\Music Library\Data\Playlist_No_Duplicates.csv'
New = r'C:\Users\mackt\Python\Music Library\Data\Music_Library.csv'

shutil.copyfile(Original, New)

'C:\\Users\\mackt\\Python\\Music Library\\Data\\Music_Library.csv'

In [381]:
song1 = {}

with open(r'C:\Users\mackt\Python\Music Library\Data\Playlist_No_Duplicates.csv', newline='', encoding='utf-8') as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        song1['song{0}'.format(row['ID'])] = {}

        # # "U" in "To U"
        # if 'Ãoe' in row['Song']:
        #     s = row['Artist 1'].split('Ã«')
        #     s.append(s[1])
        #     s[1] = 'U'
        #     s = ''.join(s)
        #     song1['song{0}'.format(row['ID'])]['Song'] = s

        s = row['Song'].split(' (')
        s = s[0].split(' feat.')
        s = s[0].split(' -')
        song1['song{0}'.format(row['ID'])]['Song'] = s[0]

        # # "e" in "Tiesto"
        # if 'Ã«' in row['Artist 1']:
        #     a = row['Artist 1'].split('Ã«')
        #     a.append(a[1])
        #     a[1] = 'e'
        #     a = ''.join(a)
        #     song1['song{0}'.format(row['ID'])]['Artist 1'] = a

        # else:
        #     song1['song{0}'.format(row['ID'])]['Artist 1'] = row['Artist 1']

        song1['song{0}'.format(row['ID'])]['Artist 1'] = row['Artist 1']
        song1['song{0}'.format(row['ID'])]['Artist 2'] = row['Artist 2']
        song1['song{0}'.format(row['ID'])]['Spot_Date'] = row['Spot_Date']

# print(song)

In [382]:
song2 = {}

with open(r'C:\Users\mackt\Python\Music Library\Data\Music Collection (Jul 09 21).csv', newline='') as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        song2['song{0}'.format(row['ID'])] = {}
        # print(row['Rating'])
        if row['Rating'] == '':
            song2['song{0}'.format(row['ID'])]['Rating'] = 'No Rating'
        else:
            song2['song{0}'.format(row['ID'])]['Rating'] = float(row['Rating'])
        s = row['Song'].split(' (')
        s = s[0].split(' feat.')
        s = s[0].split(' - ')
        song2['song{0}'.format(row['ID'])]['Song'] = s[0]
        song2['song{0}'.format(row['ID'])]['Artist 1'] = row['Artist 1']
        song2['song{0}'.format(row['ID'])]['Artist 2'] = row['Artist 2']
        if row['Year'] == '':
            song2['song{0}'.format(row['ID'])]['Re_Date'] = 'Unknown'
        else:
            song2['song{0}'.format(row['ID'])]['Re_Date'] = row['Year']
# print(song2)

In [383]:
df = pd.read_csv(New)
df = df.copy()

F = 0
NR = 0
CL = 0

for y in range(1, len(song1)+1): # No_Dups
    s1 = song1['song{0}'.format(y)]['Song']
    a1 = song1['song{0}'.format(y)]['Artist 1']
    for i in range (1, len(song2)+1): # MusicColl
        s2 = song2['song{0}'.format(i)]['Song']
        a21 = song2['song{0}'.format(i)]['Artist 1']
        a22 = song2['song{0}'.format(i)]['Artist 2']

        if (s1 == s2 and a1 == a21) or (s1 == s2 and a1 == a22):
            df.loc[y-1, 'Re_Date'] = song2['song{0}'.format(i)]['Re_Date']
            if df.loc[y-1, 'Rating'] != '-':
                df.loc[y-1, 'Rating'] = song2['song{0}'.format(i)]['Rating']
                F = F + 1
            else:
                NR = NR + 1
            break
        # elif s1 == s2:
            # print(y, s1, a1)
            # print(i, s2, a21, a22)
            # print()
        elif i == len(song2):
            df.loc[y-1, 'Rating'] = 'Can\'t Locate'
            df.loc[y-1, 'Re_Date'] = 'Unknown'
            CL = CL + 1
            # print(s1, '\n')

    if df.loc[y-1, 'Spot_Date'] != 'Unknown' and df.loc[y-1, 'Re_Date'] != 'Unknown':
        if int(df.loc[y-1, 'Spot_Date'][:4]) <= int(df.loc[y-1, 'Re_Date']):
            df.loc[y-1, 'Date'] = df.loc[y-1, 'Spot_Date'][:4]
        elif int(df.loc[y-1, 'Spot_Date'][:4]) >= int(df.loc[y-1, 'Re_Date']):
            df.loc[y-1, 'Date'] = df.loc[y-1, 'Re_Date']
    elif df.loc[y-1, 'Spot_Date'] != 'Unknown':
        df.loc[y-1, 'Date'] = df.loc[y-1, 'Spot_Date'][:4]
    elif df.loc[y-1, 'Re_Date'] != 'Unknown':
        df.loc[y-1, 'Date'] = df.loc[y-1, 'Re_Date']
    else:
        df.loc[y-1, 'Date'] = 'Unknown'

# Implement Changes to csv
df.to_csv(r'C:\Users\mackt\Python\Music Library\Data\Music_Library.csv', index =False)

In [384]:
print('Found:', F+NR, '(%.2f%%)' %(F/len(song1)*100))
print('Can\'t Locate:', CL, '(%.2f%%)' %(CL/len(song1)*100))
# df['Rating'].value_counts()
df.groupby(['Rating']).count()

Found: 3918 (87.97%)
Can't Locate: 536 (12.03%)

,ID,Local,Num_Duplicates,Song,Artist 1,Artist 2,Artist 3,Artist 4,Artist 5,Artist 6,...,Artist URI 1,Artist URI 2,Artist URI 3,Artist URI 4,Artist URI 5,Artist URI 6,Artist URI 7,Artist URI 8,Artist URI 9,Artist URI 10
Rating,,,,,,,,,,,,,,,,,,,,,
1.0,6,6,6,6,6,1,1,0,0,0,...,6,1,1,0,0,0,0,0,0,0
1.5,3,3,3,3,3,1,0,0,0,0,...,3,1,0,0,0,0,0,0,0,0
2.0,467,467,467,467,467,166,56,27,12,2,...,466,166,56,27,12,2,2,0,0,0
2.5,3,3,3,3,3,0,0,0,0,0,...,3,0,0,0,0,0,0,0,0,0
3.0,1065,1065,1065,1065,1065,388,134,40,12,5,...,1056,388,134,40,12,5,2,0,0,0
3.5,2,2,2,2,2,1,1,1,0,0,...,2,1,1,1,0,0,0,0,0,0
4.0,696,696,696,696,696,238,100,33,7,2,...,684,238,100,33,7,2,1,1,1,1
5.0,166,166,166,166,166,43,16,6,3,0,...,160,43,16,6,3,0,0,0,0,0
Can't Locate,536,536,536,536,520,173,64,20,6,3,...,496,173,64,20,6,3,1,0,0,0
No Rating,1510,1510,1510,1510,1510,557,156,38,9,3,...,1480,557,156,38,9,3,2,1,1,1